import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';
import '../../core/database/app_database.dart';
import '../buildings/buildings_page.dart';
class ProjectsPage extends StatefulWidget{const ProjectsPage({super.key});@override State<ProjectsPage> createState()=>_ProjectsPageState();}
class _ProjectsPageState extends State<ProjectsPage>{
 List<Map<String,dynamic>> rows=[];
 @override void initState(){super.initState();load();}
 Future<void> load()async{rows=await AppDatabase.instance.query('projects',order:'createdAt DESC');if(mounted)setState((){});}
 Future<void> edit([Map<String,dynamic>? x])async{final n=TextEditingController(text:x?['name']),l=TextEditingController(text:x?['location']),p=TextEditingController(text:x?['purpose']);final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(x==null?'مشروع جديد':'تعديل المشروع'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'الاسم')),const SizedBox(height:8),TextField(controller:l,decoration:const InputDecoration(labelText:'الموقع')),const SizedBox(height:8),TextField(controller:p,decoration:const InputDecoration(labelText:'غرض التقييم'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('حفظ'))]));if(ok==true&&n.text.trim().isNotEmpty){final data={'name':n.text.trim(),'location':l.text.trim(),'purpose':p.text.trim()};if(x==null){data.addAll({'id':const Uuid().v4(),'createdAt':DateTime.now().toIso8601String()});await AppDatabase.instance.insert('projects',data);}else await AppDatabase.instance.update('projects',data,'id=?',[x['id']]);load();}}
 Future<void> remove(Map<String,dynamic>x)async{await AppDatabase.instance.delete('projects','id=?',[x['id']]);load();}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('المشروعات')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('مشروع')),body:rows.isEmpty?const Center(child:Text('لا توجد مشروعات')):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:rows.length,itemBuilder:(c,i){final x=rows[i];return Card(child:ListTile(leading:const Icon(Icons.business),title:Text(x['name']),subtitle:Text('${x['location']}\n${x['purpose']}'),isThreeLine:true,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BuildingsPage(project:x))).then((_)=>load()),trailing:PopupMenuButton(itemBuilder:(c)=>[const PopupMenuItem(value:'edit',child:Text('تعديل')),const PopupMenuItem(value:'delete',child:Text('حذف'))],onSelected:(v)=>v=='edit'?edit(x):remove(x))));})));}}
