import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';
import '../../core/database/app_database.dart';
class DefectsPage extends StatefulWidget{final Map<String,dynamic> inspection;const DefectsPage({super.key,required this.inspection});@override State<DefectsPage> createState()=>_DefectsPageState();}
class _DefectsPageState extends State<DefectsPage>{List<Map<String,dynamic>> rows=[];@override void initState(){super.initState();load();}Future<void> load()async{rows=await AppDatabase.instance.query('defects',where:'inspectionId=?',args:[widget.inspection['id']],order:'createdAt DESC');if(mounted)setState((){});}Future<void> add()async{final d=TextEditingController();String type='شرخ',sev='متوسطة';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('تسجيل عيب'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField(value:type,items:const[DropdownMenuItem(value:'شرخ',child:Text('شرخ')),DropdownMenuItem(value:'تلف خرسانة',child:Text('تلف خرسانة')),DropdownMenuItem(value:'تآكل',child:Text('تآكل')),DropdownMenuItem(value:'هبوط/تشوه',child:Text('هبوط/تشوه')),DropdownMenuItem(value:'رطوبة/تسرب',child:Text('رطوبة/تسرب'))],onChanged:(v)=>set(()=>type=v!)),DropdownButtonFormField(value:sev,items:const[DropdownMenuItem(value:'منخفضة',child:Text('منخفضة')),DropdownMenuItem(value:'متوسطة',child:Text('متوسطة')),DropdownMenuItem(value:'مرتفعة',child:Text('مرتفعة')),DropdownMenuItem(value:'حرجة',child:Text('حرجة'))],onChanged:(v)=>set(()=>sev=v!)),TextField(controller:d,maxLines:3,decoration:const InputDecoration(labelText:'الوصف'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('حفظ'))])));if(ok==true){await AppDatabase.instance.insert('defects',{'id':const Uuid().v4(),'inspectionId':widget.inspection['id'],'elementId':'','type':type,'severity':sev,'description':d.text,'status':'مفتوح','createdAt':DateTime.now().toIso8601String(),'updatedAt':DateTime.now().toIso8601String()});load();}}
Future<void> photo(Map<String,dynamic>x)async{final p=await ImagePicker().pickImage(source:ImageSource.camera,imageQuality:75);if(p!=null){final dir=await getApplicationDocumentsDirectory();final folder=Directory(join(dir.path,'photos'));await folder.create(recursive:true);final dest=join(folder.path,'${const Uuid().v4()}${extension(p.path)}');await File(p.path).copy(dest);await AppDatabase.instance.insert('photos',{'id':const Uuid().v4(),'defectId':x['id'],'path':dest,'caption':'','createdAt':DateTime.now().toIso8601String()});}}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('العيوب المسجلة')),floatingActionButton:FloatingActionButton.extended(onPressed:add,icon:const Icon(Icons.add_alert),label:const Text('عيب')),body:ListView(padding:const EdgeInsets.all(16),children:rows.map((x)=>Card(child:ListTile(leading:const Icon(Icons.warning_amber),title:Text('${x['type']} • ${x['severity']}'),subtitle:Text(x['description']),trailing:IconButton(icon:const Icon(Icons.camera_alt),onPressed:()=>photo(x)))).toList()));}}
